In [60]:
import camelot
from tqdm import tqdm
import pandas as pd

In [61]:
df = pd.DataFrame()

for page in tqdm(range(3, 604), desc="Extracting tables"):
    table = camelot.read_pdf('BOE-A-2016-11948.pdf', pages=str(page+1))[0].df
    table = table.iloc[1:,:]
    df = pd.concat([df, table], axis=0)

Extracting tables: 100%|██████████| 601/601 [1:02:41<00:00,  6.26s/it]

In [62]:
columns = ['brand', 'model/kind', 'business_period', 'c_c', 'n_c', 'g_d', 'p_kw', 'cvf', 'co2_gkm', 'cv', 'value_2017_eu']
df.columns = columns
df['cvf'] = df['cvf'].replace(",", ".", regex=True)
df = df.apply(pd.to_numeric, downcast='integer', errors='ignore')
df = df.dropna(how='all')
df.reset_index(drop=True, inplace=True)
df

,brand,model/kind,business_period,c_c,n_c,g_d,p_kw,cvf,co2_gkm,cv,value_2017_eu
0,,,,NaN,NaN,,,NaN,NaN,,
1,ABARTH,124 1.4 Spider 170,2016-,1368.0,4.0,G,125,10.61,148.0,170,31200
2,ABARTH,124 1.4 Spider Aut. 170,2016-,1368.0,4.0,G,125,10.61,153.0,170,32800
3,ABARTH,500 1.4 T-Jet,2009-2016,1368.0,4.0,G,99,10.61,155.0,135,14000
4,ABARTH,500 1.4 T-Jet Secuencial,2009-2016,1368.0,4.0,G,103,10.61,150.0,140,15300
...,...,...,...,...,...,...,...,...,...,...,...
42022,VOLVO,XC 90 D4 Kinetic 7pl.,2015-,1969.0,4.0,D,140,13.20,139.0,190,45500
42023,VOLVO,XC 90 D4 Kinetic 7pl. Aut.,2006-2014,2400.0,5.0,D,120,16.25,212.0,163,37400
42024,VOLVO,XC 90 D4 Momentum 5pl.,2015-,1969.0,4.0,D,140,13.20,139.0,190,48200
42025,VOLVO,XC 90 D4 Momentum 7pl.,2015-,1969.0,4.0,D,140,13.20,139.0,190,49500
42026,VOLVO,XC 90 D4 Momentum 7pl. Aut.,2006-2014,2400.0,5.0,D,120,16.25,212.0,163,40300

In [63]:
df.to_csv('cars.csv', index=False)